# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [31]:
dataset = pd.read_csv('C:/Users/admin/IBM_Training/Training/ML Algorithms/Social_Network_Ads.csv')
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [32]:
x = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

## Splitting the dataset into the Training set and Test set

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [13]:
y_train.head()

143    0
369    1
36     0
76     0
56     0
Name: Purchased, dtype: int64

## Feature Scaling

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [50]:
x_test

array([[ 2.15443521, -1.0473756 ],
       [-1.66892869,  0.44921788],
       [-0.03034416,  1.571663  ],
       [ 0.42481821,  0.24775338],
       [-0.66757147,  2.23361781],
       [-0.9406689 , -1.01859496],
       [ 2.06340274, -1.19127882],
       [ 0.97101305, -1.16249818],
       [-0.84963642, -0.35664015],
       [ 0.15172079,  1.19751463],
       [ 0.15172079,  0.27653402],
       [-0.30344158,  2.26239845],
       [-1.39583126,  0.04628887],
       [ 0.33378574,  0.04628887],
       [ 1.79030532,  1.80190815],
       [-0.30344158,  1.22629527],
       [-1.66892869, -0.06883371],
       [ 0.24275326,  1.83068879],
       [-1.57789621, -0.01127242],
       [-0.39447405,  2.29117909],
       [-0.03034416, -0.29907886],
       [-1.66892869,  0.33409531],
       [ 0.42481821,  0.27653402],
       [-0.12137663, -1.36396268],
       [ 0.51585068,  0.56434046],
       [ 2.06340274,  0.50677917],
       [ 0.60688316,  1.68678557],
       [-1.66892869, -0.75956916],
       [-1.48686374,

In [38]:
print(x_test)

[[ 0.84304719 -0.59403479]
 [-1.37477303 -1.35199309]
 [-0.3140764  -0.93090514]
 [-0.12122247 -1.07126779]
 [ 1.03590112 -1.21163044]
 [-0.8926382  -1.21163044]
 [-1.47119999 -0.65017985]
 [ 0.07163146 -0.28523696]
 [ 0.36091236 -0.03258419]
 [-0.3140764   0.22006858]
 [-0.8926382   0.10777846]
 [-0.69978427 -0.00451166]
 [-0.50693033 -0.84668756]
 [-1.08549213  0.52886641]
 [ 1.51803595  0.92188183]
 [-0.3140764  -0.34138202]
 [ 0.16805843  0.02356087]
 [-1.18191909  0.24814111]
 [-1.37477303 -1.46428321]
 [-0.41050337 -0.7905425 ]
 [ 1.42160898  0.02356087]
 [-0.79621123 -1.57657333]
 [-0.50693033 -0.06065672]
 [-1.18191909 -1.09934032]
 [ 0.26448539  0.02356087]
 [-1.27834606  0.24814111]
 [-0.69978427 -0.14487431]
 [-1.95333482 -0.76246997]
 [ 0.07163146 -0.00451166]
 [-0.3140764   0.55693894]
 [ 0.26448539 -0.2290919 ]
 [ 0.93947415  1.96056544]
 [ 0.93947415 -1.18355791]
 [-0.69978427  0.07970593]
 [ 0.65019325 -0.73439744]
 [-1.47119999 -0.2290919 ]
 [ 1.42160898  0.30428617]
 

## Training the Logistic Regression model on the Training set

In [35]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train, y_train)

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

## Predicting a new result

In [36]:
print(classifier.predict(sc.transform([[30,87000]])))

[0]


In [37]:
y_test.head()

355    1
165    0
308    1
288    0
168    1
Name: Purchased, dtype: int64

## Predicting the Test set results

In [38]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

## Making the Confusion Matrix

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test,y_pred))

[[77  1]
 [11 31]]
0.9
              precision    recall  f1-score   support

           0       0.88      0.99      0.93        78
           1       0.97      0.74      0.84        42

    accuracy                           0.90       120
   macro avg       0.92      0.86      0.88       120
weighted avg       0.91      0.90      0.90       120

