In [1]:
import numpy as np

In [11]:
# copy create
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 6
print(arr)
print(x)
print(x.base)

[6 2 3 4 5]
[1 2 3 4 5]
None


In [10]:
# Any changes made to the view or base will reflect in both the copies
arr = np.array([1,2,3,4,5])
y = arr.view()
print(y)

y[1] = 6

print(y)
print(arr)

print(y.base)

[1 2 3 4 5]
[1 6 3 4 5]
[1 6 3 4 5]
[1 6 3 4 5]


In [14]:
print(arr.shape)

(5,)


In [22]:
arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [24]:
arr = np.arange(27).reshape(3,3,3)
print(arr)
print(arr.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
(3, 3, 3)


In [35]:
arr = np.arange(9).reshape(3,3)
print(arr)
print()
arr = arr.reshape(-1)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2 3 4 5 6 7 8]


In [38]:
for x in arr:
    print(x)

0
1
2
3
4
5
6
7
8


In [41]:
arr = np.arange(27).reshape(3,3,3)
print(arr)
print()
for i in range (3):
    for j in range (3):
        for  k in range (3):
            print(arr[i][j][k])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [43]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [54]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
new_arr = np.array_split(arr,3,axis = 1)
print(new_arr)

[array([[ 1,  2],
       [ 7,  8],
       [13, 14]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16]]), array([[ 5,  6],
       [11, 12],
       [17, 18]])]


In [55]:
arr = np.array([1,2,3,4,5,6,7,8,9])
x = np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int32),)


In [57]:
np.who()

Name            Shape            Bytes            Type

__              9                36               int32
arr             9                36               int32
y               5                20               int32
_36 (__)        9                36               int32
arr1            5                20               int32
arr2            5                20               int32

Upper bound on total bytes  =       132


In [63]:
arr1 = np.array([1,3,2,4,5])
arr2 = np.array([5,6,8,9,7])

arr3 = np.setdiff1d(arr1,arr2)
print(arr3)

[1 2 3 4]


find the indices of max n min along the axis of an array.

In [68]:
arr = np.array([8,5,3,8,6,0,3,5,9])
print("min = {} at index {} ".format(arr.min(),arr.argmin()))
print("max = {} at index {} ".format(arr.max(),arr.argmax()))

min = 0 at index 5 
max = 9 at index 8 


3d identity array.

In [75]:
arr = np.eye(3)
print(arr)

arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


change the dimension of an array


In [76]:
arr = np.array([1,2,3,4,5], ndmin = 5)
print(arr)

[[[[[1 2 3 4 5]]]]]
