# The Basics of NumPy Arrays

## NumPy Array Attributes

In [2]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [6]:
print("x3 ndim : {}".format(x3.ndim))
print("x3 shape : {}".format(x3.shape))
print("x3 size : {}".format(x3.size))

x3 ndim : 3
x3 shape : (3, 4, 5)
x3 size : 60


In [7]:
print("dtype :  {}".format(x3.dtype))

dtype :  int32


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [10]:
print("itemsize: {} bytes".format(x3.itemsize))
print("nbytes: {} bytes".format(x3.nbytes))

itemsize: 4 bytes
nbytes: 240 bytes


In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [13]:
arr = np.array([5,0,3,3,7,9])
print(arr)

[5 0 3 3 7 9]


In [14]:
print(arr[0])

5


In [15]:
print(arr[4])

7


To index from the end of the array, you can use negative indices:

In [16]:
print(arr[-1])

9


In [17]:
print(arr[-2])

7


In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [18]:
arr = np.array([[3, 5, 2, 4],[7, 6, 8, 8],[1, 6, 7, 7]])
arr

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [19]:
print(arr[0,0])

3


In [20]:
print(arr[2,0])

1


In [21]:
print(arr[2,-1])

7


Values can also be modified using any of the above index notation:

In [22]:
arr[0,0] = 12
arr

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [34]:
arr = np.array([3, 0, 3, 3, 7, 9.33], dtype = 'i')
print(arr)

[3 0 3 3 7 9]


## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [35]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [37]:
arr[-5:]

array([5, 6, 7, 8, 9])

In [38]:
arr[4:7]

array([4, 5, 6])

In [39]:
arr[::2]

array([0, 2, 4, 6, 8])

In [40]:
arr[1::2]

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [41]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
arr[5:0:-2]

array([5, 3, 1])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [44]:
arr = np.array([[12,  5,  2,  4],[ 7,  6,  8,  8],[ 1,  6,  7,  7]])
arr

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [45]:
arr[0:2,0:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [46]:
arr[:,0::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [47]:
arr[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [54]:
print(arr[:,0:1:1].reshape(1,3))

[[12  7  1]]


In [55]:
print(arr[0])

[12  5  2  4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [56]:
print(arr[0])

[12  5  2  4]


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [62]:
arr = np.array([[12,  5,  2,  4],[ 7,  6,  8,  8],[ 1,  6,  7,  7]])
arr

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Let's extract a $2 \times 2$ subarray from this:

In [64]:
x = arr[0:2,0:2]
print(x)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [66]:
x[0,0] = 99
print(x)

[[99  5]
 [ 7  6]]


In [67]:
print(arr)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [69]:
y = np.copy(x)
print(y)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [71]:
y[0,0] = 42
print(y)

[[42  5]
 [ 7  6]]


In [72]:
print(arr)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [75]:
arr = np.array([[1,2, 3],[4, 5, 6],[7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [85]:
arr[0,:].reshape(1,3)

array([[1, 2, 3]])

In [86]:
arr[0].reshape(1,3)

array([[1, 2, 3]])

In [95]:
arr[0].reshape(3,1)

array([[1],
       [2],
       [3]])

In [96]:
arr[0].reshape(3,1)

array([[1],
       [2],
       [3]])

We will see this type of transformation often throughout the remainder of the book.

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [103]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
arr = np.hstack((x,y))
arr

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [112]:
z = np.array([99, 99, 99])
arr = np.concatenate((x,y,z))
print(arr)

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [113]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [115]:
# concatenate along the first axis
np.concatenate([grid,grid], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [116]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [117]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])

# vertically stack the arrays
np.vstack([x,  grid ])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [119]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([ grid  , y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [120]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1,x2 ,x3)

[1 2 3] [99 99] [3 2 1]


In [122]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
upper, lower = np.vsplit(grid,2)
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [126]:
left, right = np.hsplit( grid , 2 )
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
