## Numpy 




In [1]:
import numpy as np

### Slicing in Numpy Arrays

In [2]:
arr = np.array([1,2,3,4,5])
print(arr[0:4])

[1 2 3 4]


In [3]:
print(arr[2:])

[3 4 5]


In [4]:
print(arr[:3])

[1 2 3]


In [7]:
print(arr[-3:-1])

[3 4]


In [8]:
print(arr[::2])

[1 3 5]


In [16]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
print(arr2[0,:])

[1 2 3 4]


In [23]:
print(arr2[0:2,1:3])

[[2 3]
 [6 7]]


In [28]:
# for floats
a = np.array([0.6,0.7,0.8])
print(a.dtype)

float64


In [55]:
# for strings
a = np.array(['a','ab','abc','abcd'])
print(a)
print(a.dtype)

['a' 'ab' 'abc' 'abcd']
<U4


In [31]:
arr = np.array([2354697823594678239456823495682394568, 123])
print(arr.dtype)

object


In [50]:
arr = np.array([1,2,3,4,5], dtype='int64')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [57]:
# String to Int
a = np.array(['1','2','3'])
b = a.astype('int64')
print(b)
print(b.dtype)

[1 2 3]
int64


In [62]:
a = np.array([1,2,3,4])
b = a.astype('U')
print(b)
print(b.dtype)

['1' '2' '3' '4']
<U11


In [60]:
a = np.array([0,1,-2,3])
b = a.astype('bool')
print(b)
print(b.dtype)

[False  True  True  True]
bool


In [63]:
a = np.arange(2,11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [66]:
# To print how much memory does a 
a = np.array([1,2,3,4])
print(a.nbytes)

16


In [71]:
a = np.arange(1,7).reshape(2,3).astype('int64')
print(a)
print(a.dtype)

[[1 2 3]
 [4 5 6]]
int64


In [74]:
a = np.array([1,2,3,4,5])
b = a[::-1].astype('f')
print(b)
print(b.dtype)

[5. 4. 3. 2. 1.]
float32


In [75]:
# Converting a Tuple and List into a Numpy Array

t = (1,2,3)
l = [4,5,6]

arr1 = np.array(t)
arr2 = np.array(l)

print(arr1)
print(arr2)

[1 2 3]
[4 5 6]


In [83]:
a = np.empty(10)
a[6] = 11
print(a)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [94]:
a = np.array([1,2,3,4,5,6])
b = np.array([5,6,7,8,9])
c = np.intersect1d(a,b)
print(c)

[5 6]


In [95]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.union1d(a,b)
print(c)

[1 2 3 4 5 6 7 8 9]


In [100]:
a = np.arange(16).reshape(4,4)
b, c =  