In [1]:
import numpy as np

#### 1. Create a 4X2 integer array and Prints its attributes

In [5]:
arr = np.arange(8).reshape(4,2)
print("The Total size of the Array is : {}.".format(arr.size))
print("The shape of the array is {}.".format(arr.shape))
print("Data type of elements of arr is of type : {}.".format(arr.dtype))
print("Total memory given to arr is {} bytes.".format(arr.nbytes))

The Total size of the Array is : 8.
The shape of the array is (4, 2).
Data type of elements of arr is of type : int32.
Total memory given to arr is 32 bytes.


#### 2. Create a 5X2 integer array from a range between 100 to 300 such that the difference between each  element is 20.

In [7]:
arr1 = np.arange(100,300,20).reshape(5,2)
print(arr1)

[[100 120]
 [140 160]
 [180 200]
 [220 240]
 [260 280]]


#### 3. Following is the given numpy array return array of odd rows and even columns

In [12]:
# This program assumes that the first row (index = 0) is odd row.
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24],[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)
print()

ans = sampleArray[0::2,1::2]
print(ans)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

[[ 6 12]
 [30 36]
 [54 60]]


#### 4. Write a NumPy program to create an array of 5 zeros, 5 ones, 5 fives.

In [93]:
arr1 = np.zeros(5, dtype = "i")
arr2 = np.ones(5, dtype = "i")
arr3 = np.full(5,5)

ans = np.hstack((arr1,arr2,arr3))

print("First Array :  {}".format(arr1))
print()
print("Second Array :  {}".format(arr2))
print()
print("Third Array :  {}".format(arr3))
print()
print("FINAL ANSWER :  {}".format(ans))

First Array :  [0 0 0 0 0]

Second Array :  [1 1 1 1 1]

Third Array :  [5 5 5 5 5]

FINAL ANSWER :  [0 0 0 0 0 1 1 1 1 1 5 5 5 5 5]


#### 5. Write a NumPy program to create a 4X5 array using and iterate over it.

In [22]:
arr = np.arange(20).reshape(4,5)
print("The elements in the arr are : ")
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print(arr[i][j])

The elements in the arr are : 
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


#### 6. Write a NumPy program to get the number of items, array dimensions, number of array dimensions and  the memory size of each element of a given array. 

In [27]:
arr = np.arange(20).reshape(4,5)

print("Number of Items is : {}".format(arr.size))
print("Array Dimensions is : {}".format(arr.ndim))
print("Shape of the Array is of the form : {}".format(arr.shape))
print("Memory taken by each item in arr is : {}".format(arr.itemsize))

Number of Items is : 20
Array Dimensions is : 2
Shape of the Array is of the form : (4, 5)
Memory taken by each item in arr is : 4


#### 7. Write a NumPy program to get the unique elements of an array.

In [29]:
arr = np.array([1,2,3,4,5,6,6,6,4,3,7,9,8,0,2,2,1,1,1])
print("Original array is :  {}".format(arr))
ans = np.unique(arr)
print("The updated array is :  {}".format(ans))

Original array is :  [1 2 3 4 5 6 6 6 4 3 7 9 8 0 2 2 1 1 1]
The updated array is :  [0 1 2 3 4 5 6 7 8 9]


#### 8. Write a NumPy program to create a contigious flattened array. 

In [35]:
arr = np.arange(16).reshape(2,2,2,2)
print("The original array is : ")
print(arr)
print()

ans = arr.ravel()
print("Updated array is :  ")
print(ans)

The original array is : 
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]

Updated array is :  
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


#### 9. Write a NumPy program to change the data type of an array

In [39]:
arr = np.array([1,2,3,4,5,6,7])
print(arr.dtype)

arr = arr.astype("S")
print("Updated dtype of arr :  {}".format(arr.dtype))

int32
Updated dtype of arr :  |S11


#### 10.  Write a NumPy program to create a 2-D array whose diagonal equals [1,2,3,4] and 0's elsewhere.

In [40]:
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 11. Write a NumPy program to create an array of three column types (integer, float, character). 

In [70]:
arr = np.array([1,2,3], dtype = ("i,f,c"))
ans = []
print(arr)
ans.append(arr[0][0])
ans.append(arr[1][1])
ans.append(arr[2][2])
print(ans)

[(1, 1., b'1') (2, 2., b'2') (3, 3., b'3')]
[1, 2.0, b'3']


#### 12. Write a NumPy program to count the frequency of unique values in NumPy array.

In [76]:
arr = np.array([1,2,3,4,5,6,6,6,4,3,7,9,8,0,2,2,1,1,1])
unique, count = np.unique(arr, return_counts = True)
l = []
for i in range(unique.size):
    l.append((unique[i],count[i]))
print(l)

[(0, 1), (1, 4), (2, 3), (3, 2), (4, 2), (5, 1), (6, 3), (7, 1), (8, 1), (9, 1)]


#### 13. How to create a boolean array?

In [80]:
arr = np.array([0,2,3,4,5], dtype = "bool")
print(arr)

[False  True  True  True  True]


#### 14. How to replace items that satisfy a condition without affecting the original array?

In [88]:
arr = np.arange(10)
x = np.where(arr%2==0,1,0)
print(arr)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[1 0 1 0 1 0 1 0 1 0]


#### 15. How to remove from one array those items that exist in another?

In [90]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([4,5,6,7,8])
ans = np.setdiff1d(arr1,arr2)
print(ans)

[1 2 3]
